config/routes.rb
Rails.application.routes.draw do
  # flipper route
  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  devise_for :accounts

  get "up" => "rails/health#show", as: :rails_health_check

  get "/about", to: "static#about"
  get "/contact", to: "static#contact"
  get "/cookies", to: "static#cookies"
  get "/cookies_banner", to: "static#cookies_banner"
  get "/tos", to: "static#tos"
  get "/privacy", to: "static#privacy"

  get "/app", to: "react#app"

  namespace :api, defaults: { format: :json } do
    get "/accounts/me", to: "accounts#me", as: "me_accounts"
    delete "/accounts/sign_me_out", to: "accounts#sign_me_out", as: "sign_me_out_accounts"
    resources :accounts
    resources :roles

    resources :topics

    resources :notes
  end

  # Defines the root path route ("/")
  root "static#home"
end

app/views/shared/_google_fonts.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Kodchasan:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
<link  media="print" onload="this.onload=null;this.removeAttribute('media');" href="https://fonts.googleapis.com/css2?family=Kodchasan:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />

app/views/shared/_meta_tags.html.erb
<!-- Facebook Meta Tags -->
<meta property="og:url" content="https://vexuf.com">
<meta property="og:type" content="website">
<meta property="og:title" content="Vexuf.com">
<meta property="og:description" content="">
<meta property="og:image" content="https://vexuf.com/images/logo.png">
<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="vexuf.com">
<meta property="twitter:url" content="https://vexuf.com">
<meta name="twitter:title" content="Vexuf.com">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://vexuf.com/images/logo.png">
<!-- Meta Tags Generated via https://www.opengraph.xyz -->
<meta name="description" content="">
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="theme-color" content="#083445"/>
<!-- PWA -->
<link rel="manifest" href="/manifest.json">

app/views/shared/_window_objects.html.erb
<script>
  function jsonParse(json, defaultValue) {
    try {
      return JSON.parse(json.replace(/&quot;/g, '"'));
    } catch (_e) {
      return defaultValue;
    }
  }

  function getMetaContent(name) {
    var element = document.querySelector("meta[name='" + name + "']");
    return element ? element.getAttribute('content') : null;
  }


  window.FLIPPERS = jsonParse("<%= flippers_json(current_account) %>", {});
  window.RAILS_ENV = "<%= Rails.env %>";
  window.GIT_REVISION =  jsonParse("<%= git_revision %>", {});
  window.TOASTY = {
    NOTICE: "<%= notice %>",
    ALERT: "<%= alert %>"
  };
</script>