config/routes.rb
Rails.application.routes.draw do
  # flipper route
  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  devise_for :accounts

  get "up" => "rails/health#show", as: :rails_health_check

  get "/about", to: "static#about"
  get "/contact", to: "static#contact"
  get "/cookies", to: "static#cookies"
  get "/cookies_banner", to: "static#cookies_banner"
  get "/tos", to: "static#tos"
  get "/privacy", to: "static#privacy"

  get "/app", to: "react#app"

  namespace :api, defaults: { format: :json } do
    get "/accounts/me", to: "accounts#me", as: "me_accounts"
    delete "/accounts/sign_me_out", to: "accounts#sign_me_out", as: "sign_me_out_accounts"
    resources :accounts
    resources :roles

    resources :topics

    resources :notes
  end

  # Defines the root path route ("/")
  root "static#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark">
  <head>
    <title>Vexuf 24</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render partial: "shared/meta_tags" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render partial: "shared/window_objects" %>
  </head>
  <body>
    <%= turbo_frame_tag :cookies_banner, src: cookies_banner_path if session[:cookies_accepted].nil? %>
    <%= yield %>
    <% if resolve_layout == "application" %>
      <div id="theme-provider" >
      </div>
    <% end %>
  </body>
</html>        